### ISSUE TITLE
Change pairwise scales from 0-100 slider to 5-point Likert scale

### ISSUE THREAD

**Issue by hideodaikoku** [keio-moe/song-test#1]
Not urgent.

**Comment by hideodaikoku** [comment]
Change to updated labels in this spreadsheet. Very important!


https://docs.google.com/spreadsheets/d/1xf6re-rDVIrSp1vwpw6AM8P2OrZTguBizyrAeQS6F40/edit#gid=0

**Comment by pesavage** [comment]
2)    Change pairwise similarity scales from 0-100 slider to 5-point Likert scale
a.     類似性：「非常に似ていない」、「あまり似ていない」、「どちらとも言えない」、「少し似ている」、「非常に似ている」
b.     好み：「Aの方が非常に好き」、「Aの方が少し好き」、「どちらとも言えない」、「Bの方が非常に好き」、「Bの方が少し好き」
